[package]
name = "linktest"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustlib"
crate-type = ["staticlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
