[package]
name = "falcon_masked_test"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.8.4"
float-cmp = "0.9.0"
falcon = { path = "../falcon" }
falcon_masked = { path = "../falcon_masked" }