[package]
name = "falcon_masked"
version = "1.0.0"
edition = "2021"


[dependencies]
rand = {version = "0.8.3", features = ["getrandom"], default-features = false}
bytemuck = "1.13.0"
falcon = { path = "../falcon" }