[package]
name = "falcon_masked"
version = "1.0.0"
edition = "2021"


[dependencies]
bytemuck = "1.13.0"
rand_core = "0.6.4"
falcon = { path = "../falcon" }
randomness = { path = "../randomness", version="0.1.0", default-features = false, features = ["nostd"] }